---
version: "2.2"

services:

  node:
    build: node/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    command: mongod
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - "./mongo/:/docker-entrypoint-initdb.d/"