---
version: "2.2"

services:

  node:
    build: node/
    restart: always
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
